const res = {
  objectID: 436946,
  isHighlight: false,
  accessionNumber: "1991.287",
  accessionYear: "1991",
  isPublicDomain: true,
  primaryImage:
    "https://images.metmuseum.org/CRDImages/ep/original/DP-13655-001.jpg",
  primaryImageSmall:
    "https://images.metmuseum.org/CRDImages/ep/web-large/DP-13655-001.jpg",
  additionalImages: [],
  constituents: [
    {
      constituentID: 162094,
      role: "Artist",
      name: "Edouard Manet",
      constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500010363",
      constituentWikidata_URL: "https://www.wikidata.org/wiki/Q40599",
      gender: "",
    },
  ],
  department: "European Paintings",
  objectName: "Painting",
  title: "The Brioche",
  culture: "",
  period: "",
  dynasty: "",
  reign: "",
  portfolio: "",
  artistRole: "Artist",
  artistPrefix: "",
  artistDisplayName: "Edouard Manet",
  artistDisplayBio: "French, Paris 1832–1883 Paris",
  artistSuffix: "",
  artistAlphaSort: "Manet, Edouard",
  artistNationality: "French",
  artistBeginDate: "1832",
  artistEndDate: "1883",
  artistGender: "",
  artistWikidata_URL: "https://www.wikidata.org/wiki/Q40599",
  artistULAN_URL: "http://vocab.getty.edu/page/ulan/500010363",
  objectDate: "1870",
  objectBeginDate: 1870,
  objectEndDate: 1870,
  medium: "Oil on canvas",
  dimensions: "25 5/8 x 31 7/8 in. (65.1 x 81 cm)",
  measurements: [
    {
      elementName: "Frame",
      elementDescription: null,
      elementMeasurements: [Object],
    },
    {
      elementName: "Overall",
      elementDescription: null,
      elementMeasurements: [Object],
    },
  ],
  creditLine: "Gift and Bequest of David and Peggy Rockefeller, 1991, 2017",
  geographyType: "",
  city: "",
  state: "",
  county: "",
  country: "",
  region: "",
  subregion: "",
  locale: "",
  locus: "",
  excavation: "",
  river: "",
  classification: "Paintings",
  rightsAndReproduction: "",
  linkResource: "",
  metadataDate: "2025-03-05T04:54:35.18Z",
  repository: "Metropolitan Museum of Art, New York, NY",
  objectURL: "https://www.metmuseum.org/art/collection/search/436946",
  tags: [
    {
      term: "Bread",
      AAT_URL: "http://vocab.getty.edu/page/aat/300262820",
      Wikidata_URL: "https://www.wikidata.org/wiki/Q7802",
    },
    {
      term: "Grapes",
      AAT_URL: "http://vocab.getty.edu/page/aat/300379338",
      Wikidata_URL: "https://www.wikidata.org/wiki/Q10978",
    },
    {
      term: "Peaches",
      AAT_URL: "http://vocab.getty.edu/page/aat/300266272",
      Wikidata_URL: "https://www.wikidata.org/wiki/Q13202263",
    },
    {
      term: "Flowers",
      AAT_URL: "http://vocab.getty.edu/page/aat/300132399",
      Wikidata_URL: "https://www.wikidata.org/wiki/Q506",
    },
    {
      term: "Still Life",
      AAT_URL: "http://vocab.getty.edu/page/aat/300015638",
      Wikidata_URL: "https://www.wikidata.org/wiki/Q170571",
    },
  ],
  objectWikidata_URL: "https://www.wikidata.org/wiki/Q19905377",
  isTimelineWork: false,
  GalleryNumber: "810",
};
